version: '3.8'

services:
  # Backend Spring Boot
  backend:
    build: 
      context: ./Exam_Perez
      dockerfile: Dockerfile
    container_name: exam_perez_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network

  # Frontend React
  frontend:
    build: 
      context: ./from-web
      dockerfile: Dockerfile
    container_name: exam_perez_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:8080/api
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app_data:
